FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine as builder
WORKDIR /app
COPY ./scalable-hello-world-csharp.csproj .
RUN dotnet restore -r linux-musl-x64

COPY . /app
RUN dotnet publish -c release -o /out -r linux-musl-x64 --no-self-contained --no-restore
    
FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine-amd64 as base
WORKDIR /app
COPY --from=builder /out .
ENV ASPNETCORE_URLS=http://*:80;
ENTRYPOINT ["./scalable-hello-world-csharp"]