FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine as builder
COPY ./scalable-hello-world-csharp.csproj .
RUN dotnet restore
COPY . /app
RUN dotnet publish /app/scalable-hello-world-csharp.csproj -c Release -o /out --no-self-contained

FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine as base
COPY --from=builder /out /app
ENV ASPNETCORE_URLS=http://*:80;
ENTRYPOINT ["dotnet", "/app/scalable-hello-world-csharp.dll"]