name: Test CI/CD with Terraform 

env:
  IMAGE_TAG: asia.gcr.io/poc-general/scalable-hello-world-csharp:latest
  
on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        
#      - name: Setup .NET SDK
#        uses: actions/setup-dotnet@v2
#        with:
#          dotnet-version: '6.0.x'
          
#      - name: Build Project
#        run: |
#          cd ScalableHelloWorld
#          dotnet restore
#          dotnet build

#      - name: Run Unit Tests
#        run: |
#          cd ScalableHelloWorld.Test
#          dotnet restore
#          dotnet test

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Google Container Registry
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_CREDENTIAL }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: ScalableHelloWorld
          file: Dockerfile.gcp-cloud-run
          push: true
          tags: |
            asia.gcr.io/poc-general/scalable-hello-world-csharp:latest
            asia.gcr.io/poc-general/scalable-hello-world-csharp:${{github.ref}}